Academix.Web/Areas/Director/Controllers/SubjectController.cs
using Academix.Core.Contracts;
using Academix.Core.Models.Subject;
using Microsoft.AspNetCore.Mvc;

namespace Academix.Web.Areas.Director.Controllers
{
    public class SubjectController : DirectorBaseController
    {
        private readonly IDirectorSubjectService _subjectService;

        public SubjectController(IDirectorSubjectService subjectService)
        {
            _subjectService = subjectService;
        }

        [HttpGet]
        public async Task<IActionResult> All(string student = "")
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());
            var subjects = await _subjectService.GetSubjectsAsync(schoolId);

            if(string.IsNullOrEmpty(student))
            {
                TempData.Remove("StudentId");
            }

            return View(subjects);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());
            var teachers = await _subjectService.GetTeachersAsync(schoolId);

            var model = new AddSubjectViewModel();
            model.Teachers = teachers;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddSubjectViewModel model)
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());

            if(!await IsModelValid(schoolId, model))
            {
                var teachers = await _subjectService.GetTeachersAsync(schoolId);
                model.Teachers = teachers;

                return View(model);
            }

            await _subjectService.AddSubjectAsync(schoolId, model);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            if(await _subjectService.IsSubjectExistAsync(id))
            {
                await _subjectService.RemoveSubjectAsync(id);
            }

            return RedirectToAction(nameof(All));
        }

        private async Task<bool> IsModelValid(int schoolId, AddSubjectViewModel model)
        {
            var isValid = true;

            if (await _subjectService.IsTeacherHasSubject(model.TeacherId))
            {
                ModelState.AddModelError(string.Empty, "This teacher has subject already");

                isValid = false;
            }

            if (!await _subjectService.IsTeacherExistInSchool(schoolId, model.TeacherId))
            {
                ModelState.AddModelError(string.Empty, "This teacher doesn't exist");

                isValid = false;
            }

            return isValid;
        }
    }
}

Academix.Web/Areas/Teacher/Controllers/ClassController.cs
using Academix.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Academix.Web.Areas.Teacher.Controllers
{
    public class ClassController : TeacherBaseController
    {
        private readonly ITeacherClassService _classService;

        public ClassController(ITeacherClassService classService)
        {
            _classService = classService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var classId = await _classService.GetClassIdAsync(GetUserId());
            var students = await _classService.GetStudentsAsync(classId);

            return View(students);
        }

        [HttpGet]
        public async Task<IActionResult> AllAbsences(int id)
        {
            var absences = await _classService.GetAbsencesAsync(id);

            TempData["StudentId"] = id;

            return View(absences);
        }

        [HttpGet]
        public async Task<IActionResult> ExcuseAbsence(int id)
        {
            if (!await _classService.IsAbsenceExist(id))
            {
                return BadRequest();
            }

            await _classService.UpdatedAbsenceAsync(id);

            return RedirectToAction(nameof(AllAbsences), new { id = TempData["StudentId"] });
        }
    }
}

Academix.Web/Controllers/RequestController.cs
using Academix.Common.Constants;
using Academix.Core.Contracts;
using Academix.Infrastructure.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Academix.Web.Controllers
{
    [Authorize(Roles = $"{RoleConstants.Admin.RoleName},{RoleConstants.Director.RoleName}")]
    public class RequestController : BaseController
    {
        private readonly AcademixDbContext _context;
        private readonly IRequestService _requestService;

        public RequestController(AcademixDbContext context, IRequestService requestService)
        {
            _context = context;
            _requestService = requestService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var requests = await _requestService.GetAllRequestsAsync(GetUserId());

            return View(requests);
        }

        [HttpGet]
        public async Task<IActionResult> Accept(int id)
        {
            var request = await _requestService.GetRequestByIdAsync(id);

            if (request == null)
            {
                return RedirectToAction(nameof(All));
            }

            await _requestService.AssignToRoleAsync(request);
            await _requestService.RemoveRequestAsync(request.Id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Deny(int id)
        {
            var request = await _requestService.GetRequestByIdAsync(id);

            if (request == null)
            {
                return RedirectToAction(nameof(All));
            }

            await _requestService.RemoveRequestAsync(request.Id);

            return RedirectToAction(nameof(All));
        }

        private string GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }
}

Academix.Web/Views/Shared/_GradesPartial.cshtml
@model IEnumerable<GradeServiceModel>

@foreach (var grade in Model)
{
    @if (grade.GradeNumber == 2)
    {
        <span data-toggle="popover"
              data-bs-content="Type: @grade.GradeType | Date: @grade.DateAndTime"
              class="grade px-2 rounded-10 bg-danger text-white fs-4 fw-bold">
            @grade.GradeNumber
        </span>
    }
    else if (grade.GradeNumber == 6)
    {
        <span data-toggle="popover"
              data-bs-content="Type: @grade.GradeType | Date: @grade.DateAndTime"
              class="grade px-2 rounded-10 bg-success text-white fs-4 fw-bold">
            @grade.GradeNumber
        </span>
    }
    else
    {
        <span data-toggle="popover"
              data-bs-content="Type: @grade.GradeType | Date: @grade.DateAndTime"
              class="grade px-2 rounded-10 bg-warning text-white fs-4 fw-bold">
            @grade.GradeNumber
        </span>
    }
}

Academix.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Academix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Academix.Web.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark text-white">
    <div class="position-absolute top-50 start-50 translate-middle h-100 w-100 d-flex flex-column justify-content-between">
        @if (SignInManager.IsSignedIn(User))
        {
            <header class="mx-3 my-3">
                <nav class="rounded-10 navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
                    <div class="container-fluid mx-3">
                        <a class="navbar-brand fs-1 fw-bold ms-lg-3" asp-area="" asp-controller="Home" asp-action="Index">Academix</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item ms-lg-3">
                                    <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                                </li>
                                <partial name="_NavigationPartial" />
                            </ul>
                            <partial name="_LoginPartial" />
                        </div>
                    </div>
                </nav>
            </header>
        }

        <main class="d-flex justify-content-center align-items-center flex-column flex-wrap">
            @RenderBody()
        </main>

        @if (SignInManager.IsSignedIn(User))
        {
            <footer class="bg-white rounded-10 mx-3 my-3 footer-custom">
                <div class="container text-dark">
                    &copy; 2024 - Academix
                </div>
            </footer>
        }
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Academix.Web/Views/Shared/_NavigationPartial.cshtml
@if (User.IsStudent())
{
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Student" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    </li>
}

@if (User.IsParent())
{
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Parent" asp-controller="Student" asp-action="Index">Students</a>
    </li>
}

@if (User.IsTeacher())
{
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Teacher" asp-controller="Class" asp-action="Index">MyClass</a>
    </li>
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Teacher" asp-controller="Student" asp-action="Index">Students</a>
    </li>
}

@if (User.IsDirector())
{
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="" asp-controller="Request" asp-action="All">Requests</a>
    </li>
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Director" asp-controller="Subject"
           asp-route-student="" asp-action="All">Subjects</a>
    </li>
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="Director" asp-controller="Student" asp-action="All">Students</a>
    </li>
}

@if (User.IsAdmin())
{
    <li class="nav-item ms-lg-3">
        <a class="text-whiteblue fs-3 fw-bold text-decoration-none" asp-area="" asp-controller="Request" asp-action="All">Requests</a>
    </li>
}