Academix.Web/Models/Request/AllViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Academix.Web.Models.Request
{
    public class AllViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Role { get; set; } = null!;

        [Required]
        public string RequesterName { get; set; } = null!;

        public string? Message { get; set; }
    }
}

Academix.Web/Areas/Director/Controllers/SubjectController.cs
using Academix.Core.Contracts;
using Academix.Core.Models.Subject;
using Microsoft.AspNetCore.Mvc;

namespace Academix.Web.Areas.Director.Controllers
{
    public class SubjectController : DirectorBaseController
    {
        private readonly IDirectorSubjectService _subjectService;

        public SubjectController(IDirectorSubjectService subjectService)
        {
            _subjectService = subjectService;
        }

        [HttpGet]
        public async Task<IActionResult> All(string student = "")
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());
            var subjects = await _subjectService.GetSubjectsAsync(schoolId);

            if(string.IsNullOrEmpty(student))
            {
                TempData.Remove("StudentId");
            }

            return View(subjects);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());
            var teachers = await _subjectService.GetTeachersAsync(schoolId);

            var model = new AddSubjectViewModel();
            model.Teachers = teachers;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddSubjectViewModel model)
        {
            var schoolId = await _subjectService.GetSchoolIdAsync(GetUserId());

            if(!await IsModelValid(schoolId, model))
            {
                var teachers = await _subjectService.GetTeachersAsync(schoolId);
                model.Teachers = teachers;

                return View(model);
            }

            await _subjectService.AddSubjectAsync(schoolId, model);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            if(await _subjectService.IsSubjectExistAsync(id))
            {
                await _subjectService.RemoveSubjectAsync(id);
            }

            return RedirectToAction(nameof(All));
        }

        private async Task<bool> IsModelValid(int schoolId, AddSubjectViewModel model)
        {
            var isValid = true;

            if (await _subjectService.IsTeacherHasSubject(model.TeacherId))
            {
                ModelState.AddModelError(string.Empty, "This teacher has subject already");

                isValid = false;
            }

            if (!await _subjectService.IsTeacherExistInSchool(schoolId, model.TeacherId))
            {
                ModelState.AddModelError(string.Empty, "This teacher doesn't exist");

                isValid = false;
            }

            return isValid;
        }
    }
}

Academix.Web/Areas/Parent/Controllers/StudentController.cs
using Academix.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Academix.Web.Areas.Parent.Controllers
{
    public class StudentController : ParentBaseController
    {
        private readonly IParentStudentService _parentHomeService;

        public StudentController(IParentStudentService parentHomeService)
        {
            _parentHomeService = parentHomeService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var students = await _parentHomeService.GetStudentsInfoAsync(GetUserId());

            return View(students);
        }

        private string GetUserId()
        {
            return User.FindFirstValue(ClaimTypes.NameIdentifier);
        }
    }
}

Academix.Web/Areas/Director/Views/Subject/Add.cshtml
@model AddSubjectViewModel

@{
    ViewData["Title"] = "Add Subject";
}

<div class="bg-auth rounded-10">
    <div class="text-center text-white fs-3 fw-normal pt-3">Subject</div>
    <hr class="bg-white mx-4 my-3" />
    <form method="post" class="d-flex flex-column">
        <div asp-validation-summary="ModelOnly" id="alerts" class="text-danger fw-bold" role="alert"></div>
        <div class="d-flex flex-column justify-content-between">
            <div class="mx-4">
                <label asp-for="Name" class="d-block text-white fs-5">Name</label>
                <input asp-for="Name" class="d-block w-100 form-control" aria-required="true" />
                <span asp-validation-for="Name" class="text-danger fw-bold"></span>
            </div>
            <div class="mx-4">
                <label asp-for="TeacherId" class="form-label-add-edit fs-5">Teacher</label>
                <select asp-for="TeacherId" class="form-control" aria-required="true">
                    <option value="" selected disabled hidden>Select teacher</option>
                    @foreach (var teacher in Model.Teachers)
                    {
                        <option value="@teacher.Id">@teacher.Name</option>
                    }
                </select>
                <span asp-validation-for="TeacherId" class="text-danger fw-bold"></span>
            </div>
        </div>
        <div class="d-flex flex-row mx-4 justify-content-between py-4">
            <a asp-controller="Subject" asp-action="All" class="w-20 btn btn-lg btn-primary">Cancel</a>
            <button asp-controller="Subject" asp-action="Add" type="submit" class="w-20 btn btn-lg btn-primary">Add</button>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Academix.Web/Areas/Director/Views/Subject/All.cshtml
@model IEnumerable<AllViewModel>
@inject IDirectorStudentService Service

@{
    ViewData["Title"] = "Subjects";
}

<div class="mb-5 text-center">
    <h1 class="display-1 fw-bold ">Subjects</h1>

    @if (Model.Count() == 0)
    {
        <h2 class="display-4 text-danger">No subjects</h2>
    }
</div>

@if (TempData.Peek("StudentId") == null)
{
    <a asp-controller="Subject" asp-action="Add" class="btn btn-primary w-25">Add</a>
}

<div class="container-fluid bg-transparent my-4 p-3">
    <div class="row row-cols-1 row-cols-xs-2 row-cols-sm-2 row-cols-lg-6 g-3 text-center d-flex flex-wrap justify-content-center">
        @foreach (var subject in Model)
        {
            <div class="col">
                <div class="rounded-10 bg-auth card h-100 shadow-sm">
                    <div class="card-body align-content-center">
                        <div class="mb-3">
                            <div>
                                <div class="d-block text-white fs-4 fw-normal">Subject</div>
                                <span class="text-white fs-4 fw-bold">@subject.Name</span>
                            </div>
                            <hr class="bg-white mx-3 my-1" />
                            <div>
                                <div class="d-inline text-white fs-5 fw-normal">Teacher:</div>
                                <span class="text-white fs-5 fw-bold">@subject.Teacher</span>
                            </div>
                        </div>
                        @if (TempData.Peek("StudentId") == null)
                        {
                            <a asp-controller="Subject" asp-action="Remove" asp-route-id="@subject.Id" class="btn btn-primary w-75">Remove</a>
                        }
                        else
                        {
                            @if (await Service.IsStudentHasSubjectAsync((int)TempData.Peek("StudentId"), subject.Id))
                            {
                                <a asp-controller="Student" asp-action="RemoveSubject" asp-route-id="@subject.Id"
                                   asp-route-studentId="@TempData.Peek("StudentId")" class="btn btn-primary w-75">Remove</a>
                            }
                            else
                            {
                                <a asp-controller="Student" asp-action="AddSubject" asp-route-id="@subject.Id"
                                   asp-route-studentId="@TempData.Peek("StudentId")" class="btn btn-primary w-75">Add</a>
                            }
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>